
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-Placeholder","number":96,"title":"Hancheng menu item review placeholder","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/96"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-edit","number":94,"title":"Added ucsborg edit","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/94"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-index","number":89,"title":"Added ucsborg index","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/89"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-create","number":85,"title":"Added ucsborg create","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/85"}]
