
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequest-Fixtures","number":66,"title":"Adding fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/66"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequest-Backend","number":65,"title":"Copying over HelpRequest Backend files from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/65"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-backend","number":64,"title":"Copied MenuItemReview to team03","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/64"},{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"Alex-RecRequestCopyBackend","number":63,"title":"Copied backend files from team02 to team03 for Recommendation Request","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/63"},{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-dining-backend","number":62,"title":"Copied over backend from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-copy","number":61,"title":"copied team02 files for UCSB org","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/61"}]
