
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequest-Component-Table","number":79,"title":"Adding table and utils for HelpRequest and their tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/79"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-table","number":78,"title":"added ucsb org table, tests, storybook","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/78"},{"author":{"id":"U_kgDOBtX_Tw","is_bot":false,"login":"bradenc24","name":""},"headRefName":"Braden-HelpRequest-Component","number":77,"title":"Adding HelpRequest form, stories, and tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/77"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-form-component","number":76,"title":"Added UCSB org form, tests, and storybook ","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/76"},{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-dining-form","number":75,"title":"Created component and set up form and storybook for form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/75"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-Form","number":74,"title":"Amgad Articles Form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/74"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-Fixtures","number":73,"title":"Amgad articles fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/73"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-CreateFixtures","number":68,"title":"Hancheng menu item review create fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/68"}]
