
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-Form","number":74,"title":"Amgad Articles Form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/74"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-Fixtures","number":73,"title":"Amgad articles fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/73"},{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"RecRequestFixtures","number":71,"title":"ax - added fixtures file for recommendation request","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/71"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsb-org-fixtures","number":70,"title":"added ucsb org fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/70"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-CreateFixtures","number":68,"title":"Hancheng menu item review create fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/68"}]
