
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-MenuItemReview-Form","number":82,"title":"form and tests completed","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/82"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-ucsborg-placeholder","number":81,"title":"added placeholders for ucsb org","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/81"},{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-dining-table","number":80,"title":"Created table and story for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/80"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-Form","number":74,"title":"Amgad Articles Form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/74"}]
