
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"AH-Articles-IndexPage","number":119,"title":"Ah articles index page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/119"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"AH-Articles-EditPage","number":118,"title":"Ah articles edit page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/118"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-App-Articles","number":116,"title":"Amgad app articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/116"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-CreatePage","number":100,"title":"Amgad articles create page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/100"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-IndexPage","number":99,"title":"Amgad articles index page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/99"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-Articles-EditPage","number":98,"title":"Amgad articles edit page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-2/pull/98"}]
